# Generated by Django 4.0.2 on 2022-07-08 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
